### ISSUE TITLE
Preview screen stops and get AVSessionCapture error -11819

### ISSUE THREAD

**Issue by pixatra5163** [Streamaxia/Android-Open-SDK#1]
The stream starts fine on iphone, but when i try to view the stream on url http://play.streamaxia.com/<my stream name> , it keeps on loading, and on device i get error:

AVCaptureSession error occured. Error Domain=AVFoundationErrorDomain Code=-11819 "Cannot Complete Action"

**Comment by speedoholic** [comment]
Facing similar issue when trying out the example project.

**Comment by mihaimotocu** [comment]
We had an issue with the default media server which has been fixed, now.
