### ISSUE TITLE
Invalid RTMP URL. Must be in format: rtmp://[username:pass@]host[:port]/application[/streamName]

### ISSUE THREAD

**Issue by Allansk2** [Streamaxia/Android-Open-SDK#15]
Hi,
I tried to to stream to Facebook, it fails with exception:
java.io.IOException: Invalid RTMP URL. Must be in format: rtmp://[username:pass@]host[:port]/application[/streamName]

I think I found the issue:
        final Pattern O = Pattern.compile("^rtmp://(\\S*):(\\S*)@([^/:]+)(:(\\d+))*(/(.*))*/([^/]+)$");
        final Pattern P = Pattern.compile("^rtmp://([^/:]+)(:(\\d+))*(/(.*))*/([^/]+)$");
   
But the rtmpUrl is something like: rtmps://live-api-s.facebook.com:443/rtmp/111941880606040?s_bl=1&s_sc=111941910606037&s_sw=0&s_vt=api-s&a=Abz-2Opv3Rc4VPse

The stream_url and secure_stream_url are the same: https://developers.facebook.com/docs/live-video-api/guides/streaming and https://developers.facebook.com/blog/post/2019/04/16/live-video-uploads-rtmps/
The pattern is only for "rtmp://", not "rtmps://". But if I change my stream url to "rtmp://live-api-s.facebook.com:443 .......", or I change the Pattern to rtmps, I got another error "java.io.IOException: Invalid RTMP protocol version; expected 3, got 21".

iOS version works fine, because there's api to set custom rtmp url.
iOS version sdk has much more api than Android version, such as changing frameRate and keyFrameInterval. Can Android sdk expose the api too?
Thanks!

**Comment by punnoket** [comment]
I have found your issue same. Wait for owner SDK resolve this issue :(

**Comment by supraweey** [comment]
I've found those errors as well.
1. When I put rtmp url on this project, it shows error "Invalid RTMP URL. Must be in format: rtmp://[username:pass@]host[:port]/application[/streamName]".

2. When I put "rtmp://" instead "rtmps://", it shows error "Invalid RTMP protocol version; expected 3, got 21".

3. Moreover, I put rtmp url on **Broadcast Me** Application, it shows "Please enter valid url" (It works on iOS app).

**Comment by Allansk2** [comment]
@supraweey 
I have exactly the same problem you have. They do have the RTMPS to be added on their roadmap in Android. The latest reply from them, they should have it ready around 14th of August. Hope there's new release next week. 

Cheers!

**Comment by Allansk2** [comment]
Issue is fixed on latest sdk.
