### ISSUE TITLE
How to go live on wowza with this sdk?

### ISSUE THREAD

**Issue by truptigoqii** [Streamaxia/Android-Open-SDK#8]

**Comment by truptigoqii** [comment]
I have tried with wowza rtmp and works for me perfectly

**Comment by deepbhavsar** [comment]
Hello @truptigoqii 
I am trying with Wowza using latest git code but I am getting socket error:

```
I/Mp4Muxer: Mp4Muxer closed
I/FlvMuxer: FlvMuxer closed
W/System.err: java.net.SocketException: Socket is closed
W/System.err:     at java.net.Socket.shutdownInput(Socket.java:1500)
W/System.err:     at com.streamaxia.android.a.b.c.c(Unknown Source)
W/System.err:     at com.streamaxia.android.a.b.a(Unknown Source)
W/System.err:     at com.streamaxia.android.c.c(Unknown Source)
W/System.err:     at com.streamaxia.android.c.f(Unknown Source)
W/System.err:     at com.streamaxia.android.c$2.run(Unknown Source)
W/System.err:     at java.lang.Thread.run(Thread.java:760)
D/RtmpConnection: socket closed
```
It is working fine sometime but sometime it is giving continueasly this error and don't start streaming.
I have tried with the different streaming name but facing the same error. sometimes it is working fine automatically after some interval of time.
I have checked my internet connection and it is perfect. Please share the solution.
